name: Update Data

on:
  schedule:
    - cron: '0 12 * * *' # Ежедневно в 12:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install Dependencies
        run: npm install node-fetch@2
      
      - name: Run Updater
        env:
          KINOPOISK_API_KEY: ${{ secrets.KINOPOISK_API_KEY }}
        run: node update-data.js
      
      - name: Commit Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Auto-update data"
          git push "https://$GH_TOKEN@github.com/mpoles/kinopoisk-cachee.git"
