name: Update Kinopoisk Cache

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 03:00 UTC
  workflow_dispatch:     # Allows manual "Run workflow" trigger in GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install axios

      - name: Fetch data and build data.json
        env:
          KINOPOISK_API_KEY: ${{ secrets.KINOPOISK_API_KEY }}
        run: |
          node ./update_cache.js
      
      - name: Commit to gh-pages branch
        uses: EndBug/add-and-commit@v9
        with:
          add: 'data.json'
          message: 'Update data.json [skip ci]'
          branch: 'mail'
